-- ------------------------------------------------------
--  File created - Friday-October-05-2018   
-- ------------------------------------------------------
-- ------------------------------------------------------
--  DDL for Table STUDENTSXCLASSES
-- ------------------------------------------------------

  CREATE TABLE `STUDENTSXCLASSES` 
   (	`STUDENTXCLASSID` INT(20) NOT NULL PRIMARY KEY, 
	`STUDENTID` BIGINT, 
	`CLASSID` BIGINT
   );
-- INSERTING into STUDENTSXCLASSES
/* SET DEFINE OFF; */
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (268,32,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (269,32,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (270,32,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (271,32,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (272,32,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (273,34,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (274,34,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (275,34,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (276,34,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (277,34,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (278,35,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (279,35,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (280,35,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (281,35,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (282,35,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (283,36,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (284,36,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (285,36,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (286,36,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (287,36,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (288,37,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (289,37,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (290,37,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (291,37,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (292,37,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (293,38,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (294,38,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (295,38,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (296,38,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (297,38,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (298,39,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (299,39,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (300,39,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (301,39,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (302,40,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (303,40,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (304,40,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (305,40,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (306,40,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (307,41,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (308,41,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (309,41,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (310,41,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (311,41,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (312,42,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (313,42,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (314,42,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (315,42,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (316,42,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (317,43,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (318,43,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (319,43,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (320,43,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (321,43,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (322,45,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (323,45,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (324,45,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (325,45,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (326,45,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (327,46,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (328,46,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (329,46,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (330,46,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (331,46,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (332,47,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (333,47,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (334,47,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (335,47,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (336,47,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (337,48,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (338,48,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (339,48,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (340,48,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (341,48,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (342,49,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (343,49,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (344,49,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (345,49,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (346,49,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (347,50,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (348,50,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (349,50,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (350,50,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (351,50,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (352,51,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (353,51,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (354,51,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (355,51,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (356,51,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (357,52,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (358,52,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (359,52,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (360,53,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (361,53,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (362,53,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (363,53,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (364,53,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (365,54,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (366,54,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (367,54,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (368,54,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (369,54,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (370,56,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (371,56,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (372,56,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (373,56,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (374,56,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (375,57,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (376,57,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (377,57,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (378,57,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (379,57,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (380,58,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (381,58,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (382,58,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (383,58,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (384,58,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (385,59,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (386,59,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (387,59,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (388,59,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (389,59,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (390,60,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (391,60,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (392,60,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (393,60,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (394,60,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (395,61,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (396,61,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (397,61,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (398,61,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (399,61,5);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (400,62,1);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (401,62,2);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (402,62,3);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (403,62,4);
Insert into STUDENTSXCLASSES (STUDENTXCLASSID,STUDENTID,CLASSID) values (404,62,5);
-- ------------------------------------------------------
--  DDL for Index STUDENTSXCLASSES_PK
-- ------------------------------------------------------

update studentsxclasses set studentid=studentid-31;